### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Kuzeyli35** [DarwinBaker/AATool#71]
OS: Microsoft Windows 10 Home
Architecture: 64-bit
Exception: Object reference not set to an instance of an object.

    at AATool.UI.Screens.UIUpdateScreen.DrawThis(Canvas canvas)

    at AATool.UI.Controls.UIControl.DrawRecursive(Canvas canvas)

    at AATool.UI.Screens.UIScreen.DrawRecursive(Canvas canvas)

    at AATool.Main.Draw(GameTime gameTime)

    at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)

    at Microsoft.Xna.Framework.Game.Tick()

    at MonoGame.Framework.WinFormsGameWindow.TickOnIdle(Object sender, EventArgs e)

    at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)

    at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)

    at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)

    at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)

    at System.Windows.Forms.Application.Run(Form mainForm)

    at MonoGame.Framework.WinFormsGameWindow.RunLoop()

    at MonoGame.Framework.WinFormsGamePlatform.RunLoop()

    at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)

    at AATool.Program.Main()

How can I solve this?

**Comment by Kuzeyli35** [comment]
I deleted assets folder and run AAUpdate.exe now it look this
![Screenshot_3](https://github.com/DarwinBaker/AATool/assets/70401893/72181dc6-6572-41c4-a2ab-6aff2b7b9563)

**Comment by DarwinBaker** [comment]
Have you tried deleting the "config" folder as well? What GPU do you have?

**Comment by Kuzeyli35** [comment]
When I deleted the config file it gave this error. 
[crash_report_2023_5_23_12_14_11.txt](https://github.com/DarwinBaker/AATool/files/11541922/crash_report_2023_5_23_12_14_11.txt)
and I have asus 12 gb rtx 3080 ti oc

**Comment by Kuzeyli35** [comment]
is there any progress?

**Comment by DarwinBaker** [comment]
While I've been unable to directly reproduce the issue you've been having, I have identified a possible cause thanks to the crash report you uploaded. You'll have to let me know if it fixes your issue

The new version should be available next week. Once it is, try manually installing it by downloading the zip and extracting it to a new folder. I'll let you know on here when the update is available and I'd be happy to walk you through if you need any additional assistance!

**Comment by Kuzeyli35** [comment]
thank you for trying to help. you are very kind

**Comment by DarwinBaker** [comment]
The new version (1.6.3.0) is now available, give it a download when you have the chance and let me know if it fixes the issue you've been having

https://github.com/DarwinBaker/AATool/releases/latest
